### ISSUE TITLE
Deprecate data-types towards Arrow 1.0

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-core#114]
Towards Arrow 1.0 we want Arrow-Core to define what's a clear functional addition to the Kotlin Standard Library.

Therefore data types in Arrow Core should've proven their usefulness in Kotlin.
The following data types were discussed as candidates for removal.

- [ ] `Function0`
- [ ] `Function1`
- [ ] `Id`
- [ ] `Option`
- [ ] `Try`

Discussion: Which should be removed completely, and which should be moved to an `arrow-core-experimental`, `arrow-incubator-data` or a phatter `arrow-core-utils` module?

**Comment by JorgeCastilloPrz** [comment]
Try is already flagged as deprecated isn't it

**Comment by LordRaydenMK** [comment]
I would say `Option` still has it's use cases.... One example where you can't use `null` is with RxJava. Another one is a Room database where you need the difference between empty (as in no data) and empty list (there is data but 0 records).

**Comment by nomisRev** [comment]
@LordRaydenMK you're correct!

Actually there are other use-cases that require `Option`. i.e. you cannot generically use `null` as a signal, so you need to wrap in `Option`. [Example from Arrow Fx Coroutines](https://github.com/arrow-kt/arrow-fx/blob/sv-arrow-fx-coroutines/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ConcurrentVar.kt#L262)

This is the nesting of `Option` problem that @pakoito already mentioned before.

The motivation behind this was to slim down the API and coverage of Arrow-Core.

So I'd be in favor of keeping `Option` for that reason.

@aballano I think `Function0`/`Function1` deserve to be in a separate module besides `core`.

cc\\ @raulraja @JorgeCastilloPrz

**Comment by raulraja** [comment]
I don't think there is a use case for Option because even in the Fx Coroutines library the internal `Maybe` can be replaced by just:
```kotlin
typealias Maybe<A> = Either<Unit, A>
typealias None = Either.Left<Unit>
typealias Just<A> = Either.Right<A>
  
  override suspend fun take(): A =
    when (val m = unsafeTryTake()) {
      is None -> cancellableF(::unsafeTake)
      is Just -> m.b
    }
```

Option is IMO unidiomatic and pointless in regular Kotlin development and sends the wrong message to people saying they should be using a slower and memory unfriendly abstraction when the lang provides a better one. It's the same case as suspend vs IO and why we are demoting IO. Arrow Fx Coroutines is superior and has even more features and laws

**Comment by raulraja** [comment]
@aballano with Meta Function0, ListK etc... are just wrappers to overcome the limitation of not being able to extend ad-hoc types and make them minded. Meta removes that so all those wrappers should go as well since the type here is indeed Function0 etc but those of the standard lib.

**Comment by raulraja** [comment]
@LordRaydenMK Can you elaborate on the issue regarding Rx Java? I'm not familiar with Rx or this use case.

**Comment by LordRaydenMK** [comment]
RxJava offers (among other types) the `Observable<T>` data-type where `T` CAN NOT be `null`. Source: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls

So what you would typically do is use `Option<T>` instead of a nullable value.

**Comment by nomisRev** [comment]
@LordRaydenMK What Raul mentioned makes a lot of sense to me. I assume that would also work perfectly for your use-case since it offers the exact same benefits and API but in a single type instead of 2.

https://github.com/arrow-kt/arrow-core/issues/114#issuecomment-641211639

**Comment by LordRaydenMK** [comment]
Well, I agree that:

- `Option` is not idiomatic in Kotlin
- Wrapping the value in `Option` is less performant than Nullable types (citation needed)
- We can use `Either<Unit, A>` to emulate `Option<A>` 

and those would be reasons to remove it.

However there are also a few reasons to keep it:

- It respects the FP principles like referential transparency 
- Consistency - library authors can rely on it being there, instead of typealiases (I imagine someone using `Optional` another person using `Option`... 
- Keeping it helps migration to 1.0. It has been a part of Arrow since day 1 (citation needed) and I would assume there is a lot of code written with it 

Instead of deprecating it and later removing it, I would suggest it's moved to another module, `arrow-core-legacy` or `arrow-core-deprecated`. This will send a clear message that it should not be used and also help people using it to migrate to 1.0 easier.

**Comment by kmoynihan** [comment]
Having used (and since removed) Try across our codebase, I believe its removal now is logical. It has also been deprecated for quite a while. It encourages eager execution and there are superior alternatives such as suspend with the new fx coroutines API, so its removal may encourage devs to move in that direction and get better safety as a consequence.

As for Option, we still use it in some places for possible null value wrapping, but we have moved towards using the kotlin nullable (or Either with a sealed domain error in the left) instead. 
We don't have a uses case where we need to compose Options, so I agree with its removal as well. It also goes hand in hand with the move away from (with the 0.11 release) boxing with IO.  

Regarding the other data types, I've not used them so I can't comment on those.

**Comment by raulraja** [comment]
@LordRaydenMK we can move Option to another module like we are doing with IO so it's easy to migrate and use if someone wants to still fiddle with it.

**Comment by androidfred** [comment]
My team uses Arrow and I'd like to mention we do prefer option to Kotlin's nullable types. Option is much more clear and idiomatic FP than Kotlin's kind of not great implementation of nullable types.

**Comment by JorgeCastilloPrz** [comment]
That is a fair point of view @androidfred, but note that you can get all that by using `Either` for the same use cases, as mentioned across this conversation a couple of times.

**Comment by JoshNavi** [comment]
So about `Option<T>` being equivalent to `Either<Unit, T>`:

We have been adopting Arrow and FP practices in general in our Kotlin code at work and what doesn't make sense to me is that, in my mental model, `Unit` implies a necessarily successful side-effect has occurred, whereas `Option<T>`, to me, implies something more akin to `T || null`. I guess you can think of the return of a successful side-effect as `null` and then it makes sense? I understand that for an operation that can potentially error out, an `Either<Error, T>` or a `Result<Error, T>` is probably the better choice. Maybe its just the semantics of `null` being equivalent to a successful side-effect which is tripping me up. I'd love to get some clarification on whether or not I'm thinking about these concepts incorrectly.

BTW, I love the Arrow library and the work y'all do, thanks in advance!

**Comment by Zordid** [comment]
Deprecating Option and claiming there's a better way to express this by using nullable types in Kotlin is just *wrong*.

My use case involves extracting an element from a structure that could either be found or not found - and when it is found it can also be null in the structure.

Thus: Option<Any?> is the absolutely correct type here and it transports all of the possiblities.
a) found it and it is a non-null value like Some<Int>
b) found it and it is null - Some<null>
c) did not find it and it is - None

Saying Option promotes the wrong message is simply not true!

For me moving to Either<Unit, Any?> is just stupid.

**Comment by 1Jajen1** [comment]
@Zordid Yes, Option has uses that nullable types cannot cover and is a safer alternative to them. However nullable types are much more convenient to use because of the special lang support. This is why `Option` is no longer going to be in core.

@LordRaydenMK is working on moving it to a new module which I think is the best case here.

`Option` is both more expressive and safer to use than nullable types but it cannot reach the convenience and inbuilt support that they bring. And tbh the majority of use-cases are covered with just nullable types.

For someone new to arrow/kotlin the default should be nullable types until that is no longer sufficient simply because it is so much easier to use and easier to modify later. That is the sole reason we are moving it. (Well that and a general move away from typeclass heavy style to a different api which should ease use quite a bit)

Also `Either<Unit, A>` is equal to `Option<A>` and it would be trivial to replicate `Option`s api over a typealias or an inline class. (But this is likely not what @LordRaydenMK is doing simply because `Option` can be optimized like `Result` which `Either` can't really do^^)

**Comment by renpillay** [comment]
@LordRaydenMK is there an issue I can follow for this?

**Comment by ShalokShalom** [comment]
Option is to me, coming from the land of FSharp and Co something very fundamental and think tons of people who are already used to it from other functional languages finds it confusing to read it 'encourages to do the wrong thing'

You mean in this implementation specifically?
Maybe overhaul the implementation and keep the keyword?

Also: The current text in the documentation reads a bit shoehorned to me and the error handling documentation page says nothing about a possible deprecation. 

https://arrow-kt.io/docs/patterns/error_handling/

**Comment by raulraja** [comment]
Option is coming back undeprecated to support use cases where null is used as a signal value and can't be expressed through nullable types

**Comment by Muenze** [comment]
Thank god we are getting it back.
I have coded Scala for 3y and after switching to Kotlin i was so sad that I cannot work with String? like I could with Option<String>, namely map and flatmap it. If String? could be flatmapped I wouldn't need Option, but as long as this is not possible I would really miss Option. 
I know I cannot get all my scala stuff in kotlin, but missing Option, Try and this weird coroutine instead of Future was really hard.
After finding arrow and reading for a few min I was smiling the next 2 days because I thought it brings me back to my happy scala days. I could not get why you would deprecate Option.

Thanks for removing the deprecation!

**Comment by brezinajn** [comment]
@Muenze  You actually kinda can flatmap nullable types in Kotlin.
``` Kotlin
somethingNullable
    ?.let(f)
    ?.let(g)
```
