### ISSUE TITLE
Properly support `suspend` with `inline`

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-core#115]
Currently, it's hard to combine `suspend` with the data types found in `Arrow Core`.

This hinders from writing idiomatic functional code in Kotlin.

```kotlin
import arrow.core.Either
import arrow.core.flatMap

data class User(val name: String)
object DomainError

suspend fun fetchDataFromNetwork(id: Int): Either<DomainError, User> = TODO()

suspend fun program(): Either<DomainError, User> =
  Either.Right(1).flatMap { id ->
    fetchDataFromNetwork(id) // Suspension functions can be called only within coroutine body
  }
```

However, if we refactor `flatMap` to be `inline` it'll be allowed.

`inline fun <A, B, C> EitherOf<A, B>.flatMap(f: (B) -> Either<A, C>): Either<A, C>`

This is in conflict with #69 which proposes a duplicated `suspend` API.

This needs to happen for all data types that are not marked for deprecation in #114.

 - [x] `Either` #163 by @worldsnas
 - [x] `Validated`
 - [x] `NonEmptyList`
 - [ ] `Eval`
 - [x] `Const`
 - [x] `Ior`

**Comment by pakoito** [comment]
I believe this could be resolved with `suspend` versions of the functions instead. If we want to support it, let's do it explicitly.

`inline` allows suspension because it permits non-local returns. This is an anti-pattern for purity purposes, and can lead to very subtle bugs. It's an unintended coincidence that it's a scape hatch inside suspend functions.

Secondly, it causes bytecode bloat. Instead of having a single function on the data part of your binary, you have hundreds or thousands, each the same. This is bad for startup time and download and install time of apps.

Lastly, the same good thing about inline copypasting the code leads to runtime exceptions by bad code. Inlining, same as text macros, can and will produce bad bytecode on colliding definitions.

I don't believe we should normalize or encourage this just for a bit of adoption. Having a second `suspend` set of functions solves the same problem for cases where people want to call suspend functions inside those blocks.

Existing art:
https://docs.hhvm.com/hsl/reference/function/HH.Lib.Vec.map/
https://docs.hhvm.com/hsl/reference/function/HH.Lib.Vec.map_async/

https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.for_each
https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.for_each_concurrent

**Comment by nomisRev** [comment]
@pakoito I temporarily flagged this with `question`.

The reason for this proposal is that this is a common pattern in Kotlin std, and it's a well-understood pattern.

> inline allows suspension because it permits non-local returns. This is a smell for purity purposes, and can lead to very subtle bugs. It's an unintended coincidence that it's a scape hatch inside suspend functions.

Do we have any examples that are incorrect? I've only entered weird situations with nested `tailrec` suspend fun` that resulted in incorrect bytecode.

Both references you shared are a bit different since they don't share the same signature. Both `async` versions have `F` in the return of the lambda. So I'd argue this is not in line.

I am personally not a big fan of duplicating the API with `Async` or `Suspend` at the end to provide a duplicated `suspend` API.

**Comment by raulraja** [comment]
it should not be incorrect because if its inlined it's able to inline the code in the continuation loop. It's unsafe when it's not inlined because we are explicitly stating that the lambda may be capturing the external scope. Otherwise all Collection operators like forEach that are inline would also have the issue. This should be a non-issue in all strict places since they don't scape the stack with the new encoding for their continuations. I also have not seen an example of this issue.

**Comment by pakoito** [comment]
This is a bug in an inline function that's quite frequent:

```
fun bla() =
  list.map { return 1 }
```

**Comment by aballano** [comment]
I believe this might be related to what @pakoito is concerned about, here it seems inlining caused problems on Android projects with Proguard https://github.com/arrow-kt/arrow/issues/807

**Comment by nomisRev** [comment]
https://youtrack.jetbrains.com/issue/KT-23610

**Comment by worldsnas** [comment]
This Issue is incorrectly closed now should we re-open it?

**Comment by worldsnas** [comment]
We can not apply inline to most of the `Eval` functions.
the ones supported without much hassle: 
1. `coflatMap`
2. `map` 
even in their case, we need `crossinline`.

if we could inline `flatMap` more functions could be added but inline flatMap means we need to change access modifier to public.

**Comment by mkotsbak** [comment]
Hmm, it looks like it is not working, probably because using it through "EitherMonad.kt" (generated?), flatMap there is not inline.

**Comment by nomisRev** [comment]
@mkotsbak interface methods cannot be inlined, and thus those generated methods cannot be inlined.

However, if you're using the concrete types and their concrete methods those are `inline`d and it should work.

**Comment by mkotsbak** [comment]
@nomisRev how exactly do I do that? Are tests for this missing?

**Comment by nomisRev** [comment]
@mkotsbak the snippet at the top of this issue should work for Arrow `0.11.0`. Have you tried that snippet, with those imports?

Could you share the snippet that's not working for you with version `0.11.0`?

**Comment by mkotsbak** [comment]
Seem to work with map, which is defined in Either class, but not flatMap, which is only defined as:
`inline fun <A, B, C> EitherOf<A, B>.flatMap(f: (B) -> Either<A, C>): Either<A, C> =` and then probably not working without the typeclass and then no inline?

**Comment by nomisRev** [comment]
@mkotsbak the snippet defined above uses `flatMap, not just `map`. And uses the extension function `flatMap` as you shared above with this `import arrow.core.flatMap`.

Changing both `A, B` in `Either<A, B>` is not possible using `flatMap`, but can only be done with `bimap` where you provide `(A) -> C` and `(B) -> D`. Otherwise, I think you just want to use `when` to match on `Left` or `Right` and provide a new `Either`.

**Comment by mkotsbak** [comment]
Hmm, I refactored the code a bit, and now it works with arrow.core.flatMap import instead of arrow.core.extensions.either.monad.flatMap.

**Comment by nomisRev** [comment]
@mkotsbak, yes that makes sense since the latter is an `extensions` method which is the terminology we use for functionality projected from "typeclasses" or `interfaces` which sadly currently can't be inlined.
