### ISSUE TITLE
Option should not be removed/deprecated

### ISSUE THREAD

**Issue by Zordid** [arrow-kt/arrow-core#245]
I was very surprised to see that `Option<out A>` has been deprecated with the comment that the lang provides a better way.

The next sentence reveals, you aim at simply using a nullable type in Kotlin instead - but that's just a guess by me - by suggesting that if you cannot support nulls you should use `Either<Unit, A>`...

But the reality is: this is ONLY true when Option is used with a non-nullable A.
In my case, I would like to model something is really optional, but when it's there it can also be null!

So `Option<Any?>` can transport three states: some of something that is not null, some of something that is null and none.

I cannot really follow your train of thought that Option in general is a bad choice.

**Comment by PhBastiani** [comment]
See : https://github.com/arrow-kt/arrow-core/issues/238

**Comment by PhBastiani** [comment]
Option is moved... See https://github.com/arrow-kt/arrow-core/issues/238

**Comment by Zordid** [comment]
The problem I am in *right now* is, that it currently is marked as deprecated - which caused a lot of discussions in my project as we try to be warning free at all times.
I had to explain everybody that I do not believe that Option is going to be removed.
But the problem now lies in the current state of things... it *is* deprecated. :-(

**Comment by maxcruz** [comment]
I was surprised too when I saw the deprecation notice (and a little bit sad). I was expecting/dreaming of having a strict mode of Kotlin without null references instead of build on the top of something that means nothing. 

- Maybe/Optional is a container, an abstraction. You can't have a null wrapping another null. 
- It's way better communicating and making the code congruent. The return of a function can be nullable by design but also can return null for a JSON parsing mistake ([Gson, for instance](https://proandroiddev.com/safe-parsing-kotlin-data-classes-with-gson-4d560fe3cdd2)) or another condition.
- You can use Option in the same way you use a nullable, but the opposite not. 
- Option is the idiomatic way in most functional languages to handle the absence, and for me makes sense because it's a type you want to program just with types. Null from another perspective it's not a type; it's a condition of a referenced variable. 
- As Kotlin doesn't allow you type-safe functional programming, I'm expecting that a library that is the companion functional library allows us to represent functional builders in the same idiomatic way.
- I understand the points behind complexity, but to give an example; In a lot of Android projects that I saw using Either wrapping the use case results, it doesn't add more value than a simple result sealed class. It doesn't mean that Either should be removed; it's just that it's useful or not depending on your needs.

Sorry for the long posting :-)

**Comment by raulraja** [comment]
Option is coming back undeprecated to support use cases where null is used as a signal value and can't be expressed through nullable types
