### ISSUE TITLE
["Request"] SequenceK/FoldableK.map/flatMap inline to support suspend functions

### ISSUE THREAD

**Issue by mkotsbak** [arrow-kt/arrow-core#256]
What version are you currently using?

What would you like to see?
Similar to https://github.com/arrow-kt/arrow-core/issues/115
SequenceK.map/flatMap should be inline so that they work with suspend function parameters
Probably the same for ap(), traverse() and map2() too.

Same for FoldableK.

**Comment by nomisRev** [comment]
Hey @mkotsbak,

It's not possible to inline methods on `Foldable` since you cannot `inline` interface methods.
Its also not possible to `inline` methods on `Sequence`, only for _terminal_ operators afaik that consume the `Sequence`. That's because `Sequence` is lazy and if you call `map` nothing actually executes, unlike `List` which eagerly runs `map` for all the elements in the `List`.

Thanks for your issue reporting! Sadly this cannot be implemented.

Is there a specific use-case you're trying to solve? I think `Flow` might serve your needs better for these cases. I'd be glad to help if I can :)
